services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 main.wsgi:application
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - DEBUG=False
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DATABASE_URL=${DATABASE_URL}
      - ALLOWED_HOSTS=localhost,127.0.0.1
    deploy:
      resources:
        limits:
          memory: 4G