# Generated by Django 5.1.4 on 2024-12-09 19:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_member_generation_alter_member_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='description',
        ),
        migrations.RemoveField(
            model_name='member',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='member',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='birthplace',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='blood_type',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='hobbies',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='member',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='kabesha',
            field=models.ImageField(blank=True, null=True, upload_to='members/img/kabesha'),
        ),
        migrations.AddField(
            model_name='member',
            name='showroom_banner',
            field=models.ImageField(blank=True, null=True, upload_to='members/img/showroom_banner'),
        ),
        migrations.AddField(
            model_name='member',
            name='tiktok',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='type_member',
            field=models.CharField(choices=[('inti', 'Member Inti'), ('trainee', 'Trainee')], default='trainee', max_length=10),
        ),
    ]
